BIN = libsakusen-server-test
LIBS := -lrt -lboost_filesystem -lboost_system
LIB_DEP_NAMES = sakusen sakusen-server sakusen-comms sakusen-resources
THIS_CXXFLAGS =
THIS_LDFLAGS = -no-install

ifeq ($(ENABLE_LTDL_HACKED),yes)
LIB_DEP_NAMES += ltdl_hacked
else
LIBS += -lltdl
endif

ifeq ($(ENABLE_AVAHI),yes)
  LIBS += $(shell pkg-config --libs avahi-client)
  THIS_CXXFLAGS += $(shell pkg-config --cflags avahi-client)
endif

test-nonrecursive: $(BIN)
	./$(BIN)

