BIN = replay_recorder.la
THIS_LDFLAGS = -module
LIB_DEP_NAMES = libsakusen libsakusen-comms libsakusen-resources \
								libsakusen-server libsakusen-server-plugins
THIS_CPPFLAGS =
INSTALL_SUBDIR = sakusen

