language: cpp
dist: trusty
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - libmhash-dev
      - libboost-all-dev
      - swig
      - python-py++
      - tcl-dev
      - libsdl1.2-dev
      - libsdl-pango-dev
      - libavahi-client-dev
      - libglademm-2.4-dev
      - python-kde4-dev
      - python3-pykde4
      - python-qwt5-qt4
      - pyqt4-dev-tools
      - python3.5-dev
      # Added only because install fails without them
      - kdepim-runtime
      - akonadi-server
      - akonadi-backend-mysql
      - mysql-server-core-5.5
      - mysql-client-core-5.5
script: cp makefiles/config.mk.ubuntu config.mk && make && make test
