language: cpp
script: cp makefiles/config.mk.ubuntu config.mk && make && make test
dist: xenial
addons:
  apt:
    packages:
      - libmhash-dev
      - libboost-all-dev
      - swig
      - python-py++
      - tcl-dev
      - libsdl1.2-dev
      - libsdl-pango-dev
      - libavahi-client-dev
      - libglademm-2.4-dev
