language: cpp
script: cp makefiles/config.mk.ubuntu config.mk && make && make test
dist: xenial
before_install:
  - sudo apt-get -qq update
  - sudo apt install -y libmhash-dev libboost-all-dev swig python-py++ tcl-dev libsdl1.2-dev libsdl-pango-dev libavahi-client-dev libglademm-2.4-dev python-kde4-dev python3-pykde4 python-qwt5-qt4 pyqt4-dev-tools kdepim-runtime
