BIN = libsakusen-comms.la
# can't have -Wold-style-cast because <netinet/in.h> has #define's with one in
THIS_CXXFLAGS = -Wall -W -Wno-format -Woverloaded-virtual -Werror -O0 -g3
LIB_DEP_NAMES = libsakusen

include ../../Makefile.common

