BIN = libsakusen-comms.la
# can't have -Wold-style-cast because <netinet/in.h> has #define's with one in
THIS_CXXFLAGS = -Wno-old-style-cast
LIB_DEP_NAMES = libsakusen

include ../../Makefile.common

