BIN = liboptimal-test
LIBS = \
	-lboost_unit_test_framework$(BOOST_LIB_SUFFIX) \
	-lboost_system$(BOOST_LIB_SUFFIX)
LIB_DEP_NAMES = optimal
THIS_LDFLAGS = -no-install

# Must test in the srcdir to pick up the sample config files
test-nonrecursive: $(BIN)
	dir=`pwd` && cd $(this_srcdir) && $${dir}/$(BIN)

