BIN = tedomari
SOURCE_DIRS = ui ui/sdl game
THIS_CXXFLAGS = -Wall -W -Wno-format -Woverloaded-virtual -Werror -O0 -g3
THIS_CFLAGS = -Wall -W -Wno-format -O0 -g3
LIB_DEP_NAMES = libsakusen libsakusen-comms libsakusen-resources libsakusen-client liboptimal
LIBS = -lstdc++ -lreadline -lunicode -lSDL
INCLUDE =

include ../Makefile.common

