BIN = libsakusen-resources.la
SOURCE_DIRS = vfs
SUBDIRS = test
LIB_DEP_NAMES := sakusen sakusen-comms
LIBS := -lpng

ifeq ($(ENABLE_LTDL_HACKED),yes)
LIB_DEP_NAMES += ltdl_hacked
else
LIBS += -lltdl
endif

.PHONY: test

