NO_AUTO_COMPILING=yes

all-nonrecursive: run-sagittariusgen-from-builddir.sh

run-sagittariusgen-from-builddir.sh: $(this_srcdir)Makefile.local
	echo '#!/bin/sh' > $@
	echo 'cd $$(dirname $$(which $$0))' >> $@
	echo 'PYTHONPATH=$(top_builddir)bindings/python/libsakusen:$(top_builddir)bindings/python/libsakusen/.libs:$(top_builddir)tools/sagittariusgen python $(this_srcdir)sagittariusgen.py "$$@"' >> $@
	-chmod a+x $@

clean:
	-rm -f run-sagittariusgen-from-builddir.sh

