LIBS = -lstdc++
THIS_CXXFLAGS = -Wall -W -Wold-style-cast -Wno-format -Woverloaded-virtual -Werror -O0 -g3
THIS_LDFLAGS = -module
LIB_DEP_NAMES = libsakusen libsakusen-server
INCLUDE =

include ../../../Makefile.common

