BIN = libsakusen-client.la
LIBS = -lstdc++
LIB_DEP_NAMES = libsakusen

ifeq ($(ENABLE_AVAHI),yes)
  LIBS := $(LIBS) -lavahi-client
endif

ifneq ($(ENABLE_AVAHI),yes)
  EXCLUDE_FILES := mdnsbrowser.cpp
endif
